name: pib_gobiernos
source:
  type: parquet
  path: data.parquet
description: "PIB trimestral de Costa Rica, desagregado por sectores econ\xF3micos\
  \ y componentes, con valores a precios constantes."
columns:
- name: fecha
  type: datetime
  description: Fecha del trimestre correspondiente al dato del PIB.
- name: PIB_TC
  type: float
  description: "PIB total a precios constantes, indicador del valor total de los bienes\
    \ y servicios producidos en la econom\xEDa."
- name: PIB_Impuestos_TC
  type: float
  description: Valor de los impuestos netos de subsidios sobre los productos, a precios
    constantes.
- name: PIB_Valor_Agregado_TC
  type: float
  description: "Valor agregado bruto total de la econom\xEDa, a precios constantes."
- name: PIB_Agricultura_Silvicultura_Pesca_TC
  type: float
  description: "Producci\xF3n econ\xF3mica del sector Agricultura, Silvicultura y\
    \ Pesca ajustada por inflaci\xF3n."
- name: PIB_Minas_Canteras_TC
  type: float
  description: "Producci\xF3n del sector de Miner\xEDa y Canteras a precios constantes."
- name: PIB_Manufactura_TC
  type: float
  description: "Producci\xF3n industrial manufacturera ajustada por inflaci\xF3n."
- name: PIB_Electricidad_Agua_Saneamiento_TC
  type: float
  description: Valor agregado del sector de suministro de electricidad, agua y saneamiento.
- name: PIB_Construccion_TC
  type: float
  description: "Producci\xF3n del sector de construcci\xF3n a precios constantes."
- name: PIB_Comercio_TC
  type: float
  description: Valor agregado del comercio al por mayor y al por menor a precios constantes.
- name: PIB_Transporte_Almacenamiento_TC
  type: float
  description: "Producci\xF3n del sector transporte y almacenamiento, ajustado por\
    \ inflaci\xF3n."
- name: PIB_Informacion_Comunicaciones_TC
  type: float
  description: "Actividad econ\xF3mica de informaci\xF3n y comunicaciones a precios\
    \ constantes."
- name: PIB_Intermediacion_Financiera_Seguros_TC
  type: float
  description: "Valor agregado de la intermediaci\xF3n financiera y seguros."
- name: PIB_Servicios_Inmobiliarios_TC
  type: float
  description: Actividad del sector inmobiliario a precios constantes.
- name: PIB_Servicios_Empresariales_TC
  type: float
  description: "Servicios profesionales, cient\xEDficos y de apoyo empresarial ajustados\
    \ por inflaci\xF3n."
- name: PIB_Administracion_Publica_TC
  type: float
  description: "Gasto y producci\xF3n del sector p\xFAblico en administraci\xF3n,\
    \ defensa y servicios sociales."
- name: PIB_Educacion_TC
  type: float
  description: "Valor agregado de los servicios educativos, p\xFAblicos y privados."
- name: PIB_Salud_TC
  type: float
  description: "Producci\xF3n del sector de salud humana y asistencia social."
- name: PIB_Otros_Servicios_TC
  type: float
  description: Otros servicios personales, culturales y de esparcimiento a precios
    constantes.
- name: PIB_Demanda_Interna_TC
  type: float
  description: "Demanda interna total, suma del consumo e inversi\xF3n dom\xE9stica\
    \ ajustada por inflaci\xF3n."
- name: PIB_Consumo_Final_TC
  type: float
  description: Consumo final total, incluyendo hogares y gobierno, a precios constantes.
- name: PIB_Consumo_Hogares_TC
  type: float
  description: Consumo final de los hogares a precios constantes.
- name: PIB_Consumo_Gobierno_TC
  type: float
  description: "Consumo final del gobierno general ajustado por inflaci\xF3n."
- name: PIB_Formacion_Bruta_Capital_TC
  type: float
  description: "Formaci\xF3n bruta de capital, inversi\xF3n total en activos fijos\
    \ a precios constantes."
- name: PIB_Exportaciones_TC
  type: float
  description: Exportaciones totales de bienes y servicios a precios constantes.
- name: PIB_Importaciones_TC
  type: float
  description: Importaciones totales de bienes y servicios a precios constantes.
- name: PIB_Exportaciones_Bienes_TC
  type: float
  description: Exportaciones de bienes a precios constantes.
- name: PIB_Exportaciones_Servicios_TC
  type: float
  description: Exportaciones de servicios a precios constantes.
- name: PIB_Importaciones_Bienes_TC
  type: float
  description: Importaciones de bienes a precios constantes.
- name: PIB_Importaciones_Servicios_TC
  type: float
  description: Importaciones de servicios a precios constantes.
- name: PIB_Exportacion_Bienes_RegDef_TC
  type: float
  description: "Exportaciones de bienes del r\xE9gimen definitivo a precios constantes."
- name: PIB_Exportacion_Bienes_RegEsp_TC
  type: float
  description: "Exportaciones de bienes del r\xE9gimen especial a precios constantes."
- name: PIB_Importacion_Bienes_RegDef_TC
  type: float
  description: "Importaciones de bienes del r\xE9gimen definitivo a precios constantes."
- name: PIB_Importacion_Bienes_RegEsp_TC
  type: float
  description: "Importaciones de bienes del r\xE9gimen especial a precios constantes."
- name: PIB_Combustibles_TC
  type: float
  description: "Valor del consumo de combustibles en la econom\xEDa a precios constantes."
- name: PIB_Sin_Combustibles_TC
  type: float
  description: PIB ajustado excluyendo el componente de combustibles.
- name: PIB_RegDef_TC
  type: float
  description: "PIB del r\xE9gimen definitivo, excluyendo zonas francas y reg\xED\
    menes especiales."
- name: PIB_RegEsp_TC
  type: float
  description: "PIB del r\xE9gimen especial, que incluye zonas francas y reg\xEDmenes\
    \ aduaneros especiales."
- name: PIB_Terminos_Intercambio
  type: float
  description: "\xCDndice de t\xE9rminos de intercambio, relaci\xF3n entre precios\
    \ de exportaci\xF3n e importaci\xF3n."
- name: PIB_USD
  type: float
  description: "PIB total expresado en d\xF3lares estadounidenses corrientes."
