ANALYSIS_METRICS_PROMPT = """
Para todos los registros donde la columna 'Presidente' contiene a '[Nombre del Presidente]', calcula un resumen estadístico que incluya la media, mediana, mínimo, máximo, percentil 25 (Q1) y percentil 75 (Q3) para la siguiente lista específica de columnas:

PIB_TC
PIB_Valor_Agregado_TC
PIB_Agricultura_Silvicultura_Pesca_TC
PIB_Minas_Canteras_TC
PIB_Manufactura_TC
PIB_Electricidad_Agua_Saneamiento_TC
PIB_Construccion_TC
PIB_Comercio_TC
PIB_Transporte_Almacenamiento_TC
PIB_Informacion_Comunicaciones_TC
PIB_Financieras_Seguros_TC
PIB_Inmobiliario_TC
PIB_Actividades_Profesionales_TC
PIB_Administracion_Publica_TC
PIB_Ense_Salud_Asistencia_Social_TC
PIB_Otras_Actividades_TC
PIB_Demanda_Interna_TC
PIB_Gasto_Consumo_Final_TC
PIB_Formacion_Bruta_Capital_Fijo_TC
PIB_Exportaciones_Bienes_Servicios_TC
PIB_Importaciones_Bienes_Servicios_TC
"""